{
 "title": "MySQL Replication",
 "description": "Dashboard from Percona Monitoring and Management project. https://github.com/percona/grafana-dashboards",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"(mysql_binlog_files|mysql_slave_status_seconds_behind_master)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IO Thread Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_slave_status_slave_io_running{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_slave_status_slave_sql_running{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Replication Error No",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_slave_status_last_errno{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_read_only{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "MySQL Replication Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_slave_status_seconds_behind_master{instance=\"$host\"}",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Binlogs Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_binlog_size_bytes{instance=\"$host\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlog Data Written Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_binlog_size_bytes{instance=\"$host\"}[1h])",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Binlogs Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_binlog_files{instance=\"$host\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Binlogs Created Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_binlog_file_number{instance=\"$host\"}[1h])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Relay Log Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_slave_status_relay_log_space{instance=\"$host\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Relay Log Written Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_slave_status_relay_log_space{instance=\"$host\"}[1h])",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}